import type { Category, IconName } from './types';

export const PALETTE = [
  '#4F46E5',
  '#0EA5E9',
  '#10B981',
  '#84CC16',
  '#F59E0B',
  '#F97316',
  '#EF4444',
  '#EC4899',
  '#A855F7',
  '#14B8A6',
  '#64748B',
  '#78716C',
];

export const CATEGORY_ICONS: IconName[] = [
  'home',
  'cart',
  'car',
  'bus',
  'medkit',
  'game-controller',
  'bag-handle',
  'receipt',
  'school',
  'restaurant',
  'cafe',
  'airplane',
  'fitness',
  'paw',
  'shirt',
  'phone-portrait',
  'wifi',
  'flash',
  'water',
  'gift',
  'heart',
  'people',
  'briefcase',
  'laptop',
  'trending-up',
  'cash',
  'card',
  'wallet',
  'business',
  'construct',
  'film',
  'musical-notes',
  'book',
  'beer',
  'pricetag',
  'ellipsis-horizontal',
];

export const GOAL_ICONS: IconName[] = [
  'airplane',
  'home',
  'car',
  'school',
  'shield-checkmark',
  'heart',
  'gift',
  'laptop',
  'diamond',
  'umbrella',
  'trophy',
  'star',
];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 'exp-housing', name: 'Logement', icon: 'home', color: '#4F46E5', kind: 'expense' },
  { id: 'exp-food', name: 'Alimentation', icon: 'cart', color: '#10B981', kind: 'expense' },
  { id: 'exp-transport', name: 'Transport', icon: 'car', color: '#0EA5E9', kind: 'expense' },
  { id: 'exp-bills', name: 'Factures', icon: 'receipt', color: '#F59E0B', kind: 'expense' },
  { id: 'exp-health', name: 'Santé', icon: 'medkit', color: '#EF4444', kind: 'expense' },
  { id: 'exp-restaurant', name: 'Restaurants', icon: 'restaurant', color: '#F97316', kind: 'expense' },
  { id: 'exp-leisure', name: 'Loisirs', icon: 'game-controller', color: '#A855F7', kind: 'expense' },
  { id: 'exp-shopping', name: 'Shopping', icon: 'bag-handle', color: '#EC4899', kind: 'expense' },
  { id: 'exp-education', name: 'Éducation', icon: 'school', color: '#14B8A6', kind: 'expense' },
  { id: 'exp-other', name: 'Autres dépenses', icon: 'ellipsis-horizontal', color: '#64748B', kind: 'expense' },
  { id: 'inc-salary', name: 'Salaire', icon: 'briefcase', color: '#10B981', kind: 'income' },
  { id: 'inc-freelance', name: 'Freelance', icon: 'laptop', color: '#0EA5E9', kind: 'income' },
  { id: 'inc-invest', name: 'Investissements', icon: 'trending-up', color: '#4F46E5', kind: 'income' },
  { id: 'inc-gift', name: 'Cadeaux', icon: 'gift', color: '#EC4899', kind: 'income' },
  { id: 'inc-other', name: 'Autres revenus', icon: 'cash', color: '#64748B', kind: 'income' },
];
